// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIjSyBvTGLM6tEGjrh2jmBoRCCpZFzQo',
    appId: '1:888878558688:web:2cffc8dbdd79f779aa0f85',
    messagingSenderId: '888878558688',
    projectId: 'konkur-planner',
    authDomain: 'konkur-planner.firebaseapp.com',
    storageBucket: 'konkur-planner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCArC35RbHAyuySlxnfjsAu-4gaptd1t38',
    appId: '1:888878558688:android:8a5b81377be11644aa0f85',
    messagingSenderId: '888878558688',
    projectId: 'konkur-planner',
    storageBucket: 'konkur-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdTLXmTVDI4E1JRlK28iKryQFWl3umYKU',
    appId: '1:888878558688:ios:d47b1d064b992213aa0f85',
    messagingSenderId: '888878558688',
    projectId: 'konkur-planner',
    storageBucket: 'konkur-planner.firebasestorage.app',
    iosBundleId: 'com.example.konkurPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdTLXmTVDI4E1JRlK28iKryQFWl3umYKU',
    appId: '1:888878558688:ios:d47b1d064b992213aa0f85',
    messagingSenderId: '888878558688',
    projectId: 'konkur-planner',
    storageBucket: 'konkur-planner.firebasestorage.app',
    iosBundleId: 'com.example.konkurPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZIjSyBvTGLM6tEGjrh2jmBoRCCpZFzQo',
    appId: '1:888878558688:web:95dbba1df61e1e8baa0f85',
    messagingSenderId: '888878558688',
    projectId: 'konkur-planner',
    authDomain: 'konkur-planner.firebaseapp.com',
    storageBucket: 'konkur-planner.firebasestorage.app',
  );
}
